### ISSUE TITLE
PostRequest breaks rails application

### ISSUE THREAD

**Issue by spkprav** [AvinashSKaranth/api-controller#1]
Hi, I am using this in one of my project.

```
HashMap<String,String> params = new HashMap<String, String>();
params.put("user[email]", email.getText().toString());
params.put("user[password]", password.getText().toString());
final String result  = client.PostRequest(Constants.API_LOGIN, params);
```

As you can see, I am not posting any files here, yet, I get a bad content.

```
EOFError (EOFError):
rack (2.0.0.rc1) lib/rack/multipart/parser.rb:361:in `handle_empty_content!
```

This happens only if I do PostRequest without any files.

**Comment by AvinashSKaranth** [comment]
This library is supposed to be used only using Android client to connect to your web application.
Here you need to send the values as a <key,value> pair. Use simpler key like "email" and not "user[email]"

If you need it to work with square brackets try to passing the value with URLencoder. It might work. Not sure.

```
params.put(URLEncoder.encode("user[email]", "UTF-8"), email.getText().toString());
```

**Comment by spkprav** [comment]
Sure, I will try it out.
Thanks.
